name: Build
on:
  pull_request:
    paths-ignore:
      - "**.md"
  push:
    paths-ignore:
      - "**.md"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 📚 Git Checkout
        uses: actions/checkout@v4
      - name: 🎯 Setup Dart
        uses: dart-lang/setup-dart@v1
      - name: 📦 Install Dependencies
        run: dart pub get
      - name: ✨ Check Formatting
        run: dart format --set-exit-if-changed .
      - name: 🕵️ Analyze
        run: dart analyze --fatal-infos --fatal-warnings lib test
      - name: 🧪 Run Tests
        run: dart test
